services:
  server:
    build: ./pictures/Part_5
    container_name: my_server
    volumes:
      - ./pictures/Part_5/nginx.conf:/etc/nginx/nginx.conf
    

  ngin:
    # images: nginx
    build: .
    container_name: my_proxy
    ports: 
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    